# Generated by Django 6.0.3 on 2026-04-09 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('donor', 'Donor'), ('ngo', 'NGO'), ('volunteer', 'Volunteer'), ('admin', 'Admin')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=100)),
                ('expiry', models.DateTimeField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('match_score', models.FloatField(default=0.0)),
                ('points', models.IntegerField(default=0)),
                ('badge', models.CharField(default='Starter', max_length=50)),
                ('co2_saved', models.FloatField(default=0.0)),
                ('meals_saved', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=-1.2921)),
                ('longitude', models.FloatField(default=36.8219)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
