# Generated by Django 6.0.3 on 2026-04-14 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paypal_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_capture_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_donations', to=settings.AUTH_USER_MODEL)),
                ('ngo', models.ForeignKey(blank=True, limit_choices_to={'role': 'ngo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_money_donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
